// Generated by gencpp from file utils/DiffVel.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_DIFFVEL_H
#define UTILS_MESSAGE_DIFFVEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct DiffVel_
{
  typedef DiffVel_<ContainerAllocator> Type;

  DiffVel_()
    : header()
    , left_vel(0.0)
    , right_vel(0.0)
    , currHeading(0.0)  {
    }
  DiffVel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_vel(0.0)
    , right_vel(0.0)
    , currHeading(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_vel_type;
  _left_vel_type left_vel;

   typedef double _right_vel_type;
  _right_vel_type right_vel;

   typedef double _currHeading_type;
  _currHeading_type currHeading;





  typedef boost::shared_ptr< ::utils::DiffVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::DiffVel_<ContainerAllocator> const> ConstPtr;

}; // struct DiffVel_

typedef ::utils::DiffVel_<std::allocator<void> > DiffVel;

typedef boost::shared_ptr< ::utils::DiffVel > DiffVelPtr;
typedef boost::shared_ptr< ::utils::DiffVel const> DiffVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::DiffVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::DiffVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::DiffVel_<ContainerAllocator1> & lhs, const ::utils::DiffVel_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_vel == rhs.left_vel &&
    lhs.right_vel == rhs.right_vel &&
    lhs.currHeading == rhs.currHeading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::DiffVel_<ContainerAllocator1> & lhs, const ::utils::DiffVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::DiffVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::DiffVel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::DiffVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::DiffVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::DiffVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::DiffVel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::DiffVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e25873c95bf62df7b9548a7e2e027143";
  }

  static const char* value(const ::utils::DiffVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe25873c95bf62df7ULL;
  static const uint64_t static_value2 = 0xb9548a7e2e027143ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::DiffVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/DiffVel";
  }

  static const char* value(const ::utils::DiffVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::DiffVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 left_vel\n"
"float64 right_vel\n"
"float64 currHeading\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::DiffVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::DiffVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_vel);
      stream.next(m.right_vel);
      stream.next(m.currHeading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiffVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::DiffVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::DiffVel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_vel: ";
    Printer<double>::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    Printer<double>::stream(s, indent + "  ", v.right_vel);
    s << indent << "currHeading: ";
    Printer<double>::stream(s, indent + "  ", v.currHeading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_DIFFVEL_H
