// Generated by gencpp from file utils/Encoder.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_ENCODER_H
#define UTILS_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , left_twist(0.0)
    , right_twist(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_twist(0.0)
    , right_twist(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_twist_type;
  _left_twist_type left_twist;

   typedef double _right_twist_type;
  _right_twist_type right_twist;





  typedef boost::shared_ptr< ::utils::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::utils::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::utils::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::utils::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::Encoder_<ContainerAllocator1> & lhs, const ::utils::Encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_twist == rhs.left_twist &&
    lhs.right_twist == rhs.right_twist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::Encoder_<ContainerAllocator1> & lhs, const ::utils::Encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3130839172a03e3e11466bb4bb95e01";
  }

  static const char* value(const ::utils::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3130839172a03e3ULL;
  static const uint64_t static_value2 = 0xe11466bb4bb95e01ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/Encoder";
  }

  static const char* value(const ::utils::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 left_twist\n"
"float64 right_twist\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_twist);
      stream.next(m.right_twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_twist: ";
    Printer<double>::stream(s, indent + "  ", v.left_twist);
    s << indent << "right_twist: ";
    Printer<double>::stream(s, indent + "  ", v.right_twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_ENCODER_H
