// Generated by gencpp from file utils/pointID.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_POINTID_H
#define UTILS_MESSAGE_POINTID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct pointID_
{
  typedef pointID_<ContainerAllocator> Type;

  pointID_()
    : pointID(0)  {
    }
  pointID_(const ContainerAllocator& _alloc)
    : pointID(0)  {
  (void)_alloc;
    }



   typedef uint8_t _pointID_type;
  _pointID_type pointID;





  typedef boost::shared_ptr< ::utils::pointID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::pointID_<ContainerAllocator> const> ConstPtr;

}; // struct pointID_

typedef ::utils::pointID_<std::allocator<void> > pointID;

typedef boost::shared_ptr< ::utils::pointID > pointIDPtr;
typedef boost::shared_ptr< ::utils::pointID const> pointIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::pointID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::pointID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::pointID_<ContainerAllocator1> & lhs, const ::utils::pointID_<ContainerAllocator2> & rhs)
{
  return lhs.pointID == rhs.pointID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::pointID_<ContainerAllocator1> & lhs, const ::utils::pointID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::pointID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::pointID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::pointID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::pointID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::pointID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::pointID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::pointID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9ecd73bc27dcc76310bc664bc0605f0";
  }

  static const char* value(const ::utils::pointID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9ecd73bc27dcc76ULL;
  static const uint64_t static_value2 = 0x310bc664bc0605f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::pointID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/pointID";
  }

  static const char* value(const ::utils::pointID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::pointID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 pointID\n"
;
  }

  static const char* value(const ::utils::pointID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::pointID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pointID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::pointID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::pointID_<ContainerAllocator>& v)
  {
    s << indent << "pointID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pointID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_POINTID_H
