// Generated by gencpp from file utils/string_of_qrcode.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_STRING_OF_QRCODE_H
#define UTILS_MESSAGE_STRING_OF_QRCODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct string_of_qrcode_
{
  typedef string_of_qrcode_<ContainerAllocator> Type;

  string_of_qrcode_()
    : string_of_qrcode()  {
    }
  string_of_qrcode_(const ContainerAllocator& _alloc)
    : string_of_qrcode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _string_of_qrcode_type;
  _string_of_qrcode_type string_of_qrcode;





  typedef boost::shared_ptr< ::utils::string_of_qrcode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::string_of_qrcode_<ContainerAllocator> const> ConstPtr;

}; // struct string_of_qrcode_

typedef ::utils::string_of_qrcode_<std::allocator<void> > string_of_qrcode;

typedef boost::shared_ptr< ::utils::string_of_qrcode > string_of_qrcodePtr;
typedef boost::shared_ptr< ::utils::string_of_qrcode const> string_of_qrcodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::string_of_qrcode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::string_of_qrcode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::string_of_qrcode_<ContainerAllocator1> & lhs, const ::utils::string_of_qrcode_<ContainerAllocator2> & rhs)
{
  return lhs.string_of_qrcode == rhs.string_of_qrcode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::string_of_qrcode_<ContainerAllocator1> & lhs, const ::utils::string_of_qrcode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::utils::string_of_qrcode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::string_of_qrcode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::string_of_qrcode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::string_of_qrcode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::string_of_qrcode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::string_of_qrcode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::string_of_qrcode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e79ff6f588b017cff095149d881c6fca";
  }

  static const char* value(const ::utils::string_of_qrcode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe79ff6f588b017cfULL;
  static const uint64_t static_value2 = 0xf095149d881c6fcaULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::string_of_qrcode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/string_of_qrcode";
  }

  static const char* value(const ::utils::string_of_qrcode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::string_of_qrcode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string string_of_qrcode\n"
;
  }

  static const char* value(const ::utils::string_of_qrcode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::string_of_qrcode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.string_of_qrcode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct string_of_qrcode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::string_of_qrcode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::string_of_qrcode_<ContainerAllocator>& v)
  {
    s << indent << "string_of_qrcode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.string_of_qrcode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_STRING_OF_QRCODE_H
