# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from utils/mode_indoor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mode_indoor(genpy.Message):
  _md5sum = "dcef5ac4b0e09704e023b93597e3b078"
  _type = "utils/mode_indoor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 mode_indoor
bool set_complete_indoor
float64 abc"""
  __slots__ = ['mode_indoor','set_complete_indoor','abc']
  _slot_types = ['uint8','bool','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode_indoor,set_complete_indoor,abc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mode_indoor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mode_indoor is None:
        self.mode_indoor = 0
      if self.set_complete_indoor is None:
        self.set_complete_indoor = False
      if self.abc is None:
        self.abc = 0.
    else:
      self.mode_indoor = 0
      self.set_complete_indoor = False
      self.abc = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd().pack(_x.mode_indoor, _x.set_complete_indoor, _x.abc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.mode_indoor, _x.set_complete_indoor, _x.abc,) = _get_struct_2Bd().unpack(str[start:end])
      self.set_complete_indoor = bool(self.set_complete_indoor)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd().pack(_x.mode_indoor, _x.set_complete_indoor, _x.abc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.mode_indoor, _x.set_complete_indoor, _x.abc,) = _get_struct_2Bd().unpack(str[start:end])
      self.set_complete_indoor = bool(self.set_complete_indoor)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bd = None
def _get_struct_2Bd():
    global _struct_2Bd
    if _struct_2Bd is None:
        _struct_2Bd = struct.Struct("<2Bd")
    return _struct_2Bd
