# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from utils/obtacles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class obtacles(genpy.Message):
  _md5sum = "9f846863e66577b5d671e0a2f062d383"
  _type = "utils/obtacles"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

bool sonar_left
bool sonar_right

float32 left_dis_sonar
float32 right_dis_sonar

bool lidar
float32 left_ver_lidar
float32 right_ver_lidar
float32 angle_avoid_lidar


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','sonar_left','sonar_right','left_dis_sonar','right_dis_sonar','lidar','left_ver_lidar','right_ver_lidar','angle_avoid_lidar']
  _slot_types = ['std_msgs/Header','bool','bool','float32','float32','bool','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,sonar_left,sonar_right,left_dis_sonar,right_dis_sonar,lidar,left_ver_lidar,right_ver_lidar,angle_avoid_lidar

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obtacles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.sonar_left is None:
        self.sonar_left = False
      if self.sonar_right is None:
        self.sonar_right = False
      if self.left_dis_sonar is None:
        self.left_dis_sonar = 0.
      if self.right_dis_sonar is None:
        self.right_dis_sonar = 0.
      if self.lidar is None:
        self.lidar = False
      if self.left_ver_lidar is None:
        self.left_ver_lidar = 0.
      if self.right_ver_lidar is None:
        self.right_ver_lidar = 0.
      if self.angle_avoid_lidar is None:
        self.angle_avoid_lidar = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.sonar_left = False
      self.sonar_right = False
      self.left_dis_sonar = 0.
      self.right_dis_sonar = 0.
      self.lidar = False
      self.left_ver_lidar = 0.
      self.right_ver_lidar = 0.
      self.angle_avoid_lidar = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B2fB3f().pack(_x.sonar_left, _x.sonar_right, _x.left_dis_sonar, _x.right_dis_sonar, _x.lidar, _x.left_ver_lidar, _x.right_ver_lidar, _x.angle_avoid_lidar))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 23
      (_x.sonar_left, _x.sonar_right, _x.left_dis_sonar, _x.right_dis_sonar, _x.lidar, _x.left_ver_lidar, _x.right_ver_lidar, _x.angle_avoid_lidar,) = _get_struct_2B2fB3f().unpack(str[start:end])
      self.sonar_left = bool(self.sonar_left)
      self.sonar_right = bool(self.sonar_right)
      self.lidar = bool(self.lidar)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B2fB3f().pack(_x.sonar_left, _x.sonar_right, _x.left_dis_sonar, _x.right_dis_sonar, _x.lidar, _x.left_ver_lidar, _x.right_ver_lidar, _x.angle_avoid_lidar))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 23
      (_x.sonar_left, _x.sonar_right, _x.left_dis_sonar, _x.right_dis_sonar, _x.lidar, _x.left_ver_lidar, _x.right_ver_lidar, _x.angle_avoid_lidar,) = _get_struct_2B2fB3f().unpack(str[start:end])
      self.sonar_left = bool(self.sonar_left)
      self.sonar_right = bool(self.sonar_right)
      self.lidar = bool(self.lidar)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2fB3f = None
def _get_struct_2B2fB3f():
    global _struct_2B2fB3f
    if _struct_2B2fB3f is None:
        _struct_2B2fB3f = struct.Struct("<2B2fB3f")
    return _struct_2B2fB3f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
